theme: jekyll-theme-cayman
title: Автомастерские - Документация проекта
description: Документация по лабораторной работе №4. Вариант 10 «Автомастерские»
author: Петров Егор
repository: username/automaster-code