name: test_on_push

on: [push]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure

      - name: gcovr installation
        run: brew install gcovr

      - name: Show Coverage
        run: gcovr -r . --gcov-executable "llvm-cov gcov" --github-summary >> $GITHUB_STEP_SUMMARY
