name: test_on_push

on: [push]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure

      - name: Install gcovr
        run: pip3 install gcovr --break-system-packages

      - name: Show Coverage
        run: |
          # --github-summary создаст отличную таблицу с цветами прямо в Summary
          # --exclude-unreachable-branches уберет лишний шум
          # --print-summary продублирует текст в лог для надежности
          
          python3 -m gcovr -r . build/ \
            --gcov-executable "llvm-cov gcov" \
            --github-summary \
            --exclude '.*tests.*' \
            --exclude '.*_deps.*' \
            --print-summary >> $GITHUB_STEP_SUMMARY
